server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  jackson:
    date-format: java.text.SimpleDateFormat
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://150.158.6.53:33306/forum?Unicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
